### ISSUE TITLE
Fix tests 

### ISSUE THREAD

**Issue by darenegade** [darenegade/acceptance-test-harness#26]
Ich habe mal alle Tests durchlaufen lassen und dabei sind 2 Tests fehlgeschlagen:
* jobsgridportlet_numColumns
* changeColumn

Dies scheinen aber Laufzeit Probleme zu sein.

@peter-mueller @maximilian-zollbrecht Habt ihr das auch?

**Comment by maximilian-zollbrecht** [comment]
Bei mir sind alle von testStatisticsChart fehlgeschlagen. Alle anderen waren grün.

testStatisticsChart_failureAndSuccess:
```
AssertionError:
expected: is <-8421506>
but: was <-1>
```

testStatisticsChart_success
```
AssertionError:
expected: is <-1>
but: was <-8421506>
```

testStatisticsChart _failure:
```
AssertionError:
expected: is <-65794>
but: was <-1>
```

**Comment by darenegade** [comment]
Hast du mal geschaut woran es liegt? 
Bei mir laufen die durch.

**Comment by maximilian-zollbrecht** [comment]
Die Bilder sind tatsächlich nicht identisch:
![image](https://user-images.githubusercontent.com/13729948/27343341-d8c62858-55e2-11e7-9df6-ebd0fda179af.png)
![image](https://user-images.githubusercontent.com/13729948/27343347-dea4a0ba-55e2-11e7-945e-18d7371c5cf8.png)

Vielleicht habe ich eine andere Bildschirmauflösung und die Bilder werden deshalb anders gerendert.

**Comment by darenegade** [comment]
Im Code vom Plugin wird eine feste Größe generiert, daher bin ich davon ausgegangen, dass es vom Bildschirm unabhängig ist......Komisch

**Comment by darenegade** [comment]
Aber die Fonts, die auf der Maschine zur Verfügung stehen machen einen Unterschied. Das ist blöd

**Comment by peter-mueller** [comment]
Bei mir gehen nur alle Tests mit Bildern nicht, `latestBuildsPortlet_onlyLatest` ging nur beim 2. mal

**Comment by darenegade** [comment]
Dann passe ich die Bilder Tests nochmal an
